### ISSUE TITLE
Error on initiating URCaps: name "tool_contact" is not defined

### ISSUE THREAD

**Issue by Antonione** [UniversalRobots/Universal_Robots_Client_Library#185]
### Affected Client Library version(s)

1.3.3

### What combination of platform is the Client Library running on.

Linux

### How did you install the Client Library

From ROS binary packets

### Which robot platform is the library connected to.

UR E-series robot

### Robot SW / URSim version(s)

?

### How are you using the Client Library

Through the robot teach pendant using External Control URCap

### Issue details

# Summary
*Short introduction to the issue and how it impact you and why*

## Issue details
*Detailed description help us understand the problem. Code are welcome!*

## Steps to Reproduce
*Make simple example to reproduce the issue. Try to remove dependencies to other hardware and software components, if it is possible.*

## Expected Behavior
*What did you expect and why?*

## Actual Behavior
*What did you observe? If possible please attach relevant information.*

# Workaround Suggestion
*If a workaround has been found, you are welcome to share it.*

### Relevant log output

```shell
Upon attempting to initiate URCaps via the pedant, I encountered the following error message: name "tool_contact" is not defined. After initial investigation, I surmised that the error might be related to the file /ur_client_library/external_control.urscript, which I believe interfaces with URCaps.

Within the aforementioned file, I noticed the presence of an undeclared and unimported function called tool_contact, which appears to be causing the mentioned error.
```

### Accept Public visibility

- [X] I agree to make this context public

**Comment by fmauch** [comment]
This looks like you need to update your robot's software. In the issue you mentioned that you don't know your robot's software version. It is rather simple to update: https://www.universal-robots.com/download/software-e-series/update/latest-polyscope-software-update-sw-5143-e-seriesur20/

As the [README](https://github.com/UniversalRobots/Universal_Robots_Client_Library#requirements) suggests, you'll need at least software version 3.14.3 on a CB3 or 5.9.4 on an e-Series robot.

I'll close this issue since it seems to be resolved on the user side. Please feel free to comment and/or reopen if the issue persists and is not resolved by installing a newer software on the robot.
